stages:
  - test
run-tests:
  stage: test
  script:
    - cd Authentica-app
    - dotnet restore Authentica.slnx
    - dotnet build Authentica.slnx --no-restore
    - dotnet test Authentica-app.Tests/
