<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-Authentica_app-cf7cabaa-93cc-4aff-8a14-ff894951a458</UserSecretsId>
        <RootNamespace>Authentica_app</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Include="wwwroot\images\authentica.png" />
        <Compile Remove="Authentica-app.Tests/**" />
        <Content Remove="Authentica-app.Tests/**" />
        <EmbeddedResource Remove="Authentica-app.Tests/**" />
        <None Remove="Authentica-app.Tests/**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.24"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.24"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.24"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24"/>
    </ItemGroup>

</Project>
