<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-Authentica_app-cf7cabaa-93cc-4aff-8a14-ff894951a458</UserSecretsId>
        <RootNamespace>Authentica_app</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Include="wwwroot\images\authentica.png" />
        <Compile Remove="Authentica-app.Tests/**" />
        <Compile Remove="Authentica.BLL/**" />
        <Compile Remove="Authentica.DAL/**" />
        <Content Remove="Authentica.BLL/**" />
        <Content Remove="Authentica.DAL/**" />
        <Content Remove="Authentica-app.Tests/**" />
        <EmbeddedResource Remove="Authentica-app.Tests/**" />
        <None Remove="Authentica-app.Tests/**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.24" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="Authentica.BLL\Authentica.BLL.csproj" />
      <ProjectReference Include="Authentica.DAL\Authentica.DAL.csproj" />
    </ItemGroup>

</Project>
